# This YAML file is used to generate the instrumentation

---

# Parameters to define the architecture (see full description of parameters in the docs folder)
N: 8            # Input vector width
M: 4            # Number of range filters in filter unit
IB_DEPTH: 32    # Input buffer depth
FUVRF_SIZE: 4   # Size of FUVRF in M*elements
VVVRF_SIZE: 8   # Size of VVVRF in N*elements
TB_SIZE: 8      # Size of Trace Buffer in N*elements
MAX_CHAINS: 8   # Maximum number of chains of the firmware
DATA_WIDTH: 32  # Number of bits to encode each vector element
DELTA_SLOTS: 4  # Maximum number of deltas to compress into one word
DATA_TYPE: 'fixed_point' # fixed point or integer

# Define how building blocks are connected
BUILDING_BLOCKS: 
    - InputBuffer
    - FilterReduceUnit
    - VectorVectorALU
    - VectorScalarReduce
    - DataPacker
    - DeltaCompressor
    - TraceBuffer

# Define the initial firmware (see complete list at src/firmware/firmware.py)
FIRM: distribution
